language: python

env:
    - Co

matrix:
    include:
        - os: linux
          python: 3.7
          env: TOXENV=py37
        - os: osx
          osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
          language: shell       # 'language: python' is an error on Travis CI macOS
        - os: windows
          language: sh
          python: "3.7"
          before_install:
            - choco install python3
            - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"

install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; 
    then pip3 install --upgrade pip --user; 
    else pip3 install --upgrade pip;
    fi
  - pip3 install -r requirements.txt
  - pip3 install coverage

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; 
    then coverage run MainTestSuite.py;
    else python3.7 MainTestSuite.py;
    fi
 
after_succes:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; codecov -t=b8350209-0b8c-4993-8800-bbd630b0a8af; fi
