language: python

matrix:
    include:
        - os: linux
          python: 3.7
          env: TOXENV=py37
        - os: osx
          language: generic
          env: TOXENV=py37

install:
  - pip install -r requirements.txt

script:
  - python MainTestSuite.py
